---
# Required
min_players_in_bed: 1
prcnt_players_in_bed: 0.30 # Percent of players in overworld that needs to be sleeping
delay: 60  # delay in ticks from player getting into bed to starting to skip the night
interval: 20  # interval in ticks between time changes
rate: 240  # rate at which the time changes

# Optional
# Disable hover text with a tylde ~
# message_hover_text: ~
message_hover_text: 'Click me to kick everyone out of bed!'

# You can use color codes ( i.e. &4 for red, &r to reset colors )
# %playername% will be substituted with player names
kicked_from_bed_messages:
  - "%playername% doesn't want you to sleep"
# In addition to above substitutions, you can use:
# %sleeping% - number of people currently in bed
# %threshold% - number of people needed to skip the night
enter_bed_messages:  # list of messages that will be displayed
  - '%playername% is saving logs'
  - '&a%playername%&r crashed... hard...'
