---
# Required
min_players_in_bed: 1
prcnt_players_in_bed: 0.30 # Percent of players in overworld that needs to be sleeping
delay: 60  # delay in ticks from player getting into bed to starting to skip the night
interval: 20  # interval in ticks between time changes
rate: 240  # rate at which the time changes
can_players_kick: true  # whether or not other players can kick sleeping ones out of bed
# Optional (use tylde ~ to disable)
enter_bed_messages:  # list of messages that will be displayed
  - '%playername% is saving logs'
  - '&a%playername%&r crashed... hard...'
message_hover_text: 'Click me to kick everyone out of bed!'
kicked_from_bed_messages:
  - "%playername% doesn't want you to sleep"

